# Generated by Django 3.1 on 2020-09-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoarticle',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
